#! /usr/bin/env python3
# Define a Student class with attributes and a method
class Student:
	def __init__(self, name, grade, age):
		self.name = name
		self.grade = grade
		self.age = age

	def introduce(self):
		return f"Hi, I'm {self.name}, {self.age} years old, and in grade {self.grade}."


# Example: check output
# Input methodology: prompt user for input
def main():
	name = input("Enter student's name: ").strip()
	grade = input("Enter student's grade: ").strip()
	age_str = input("Enter student's age: ").strip()
	try:
		age = int(age_str)
	except ValueError:
		age = 0

	student = Student(name, grade, age)
	print(student.introduce())

	# Analyze the code generated by AI tool:
	# Attributes name, grade, and age are defined for the Student class.
	# The introduce() method returns a formatted introduction string.
	# Input is taken from user using input() for name, grade, and age.
	# Values are then used to create a Student instance and output their introduction.


if __name__ == "__main__":
	main()
